[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
sea-orm = { version = "1.1.7" }
serde = { version = "1.0.219", features = ["derive"] }
